### Get ALL
GET http://localhost:3001/api/notes 
### Get by id
GET http://localhost:3001/api/notes/6a732c1b72bd231d827e4163



### POST
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "John Johnes",
    "important": false
}
### Update
PUT http://localhost:3001/api/notes/6a72f1885fa5c514a64c541a
Content-Type: application/json

{
    "content": "John Johnes",
    "important": true
}
### Delete
DELETE http://localhost:3001/api/notes/6a732c1b72bd231d827e4163
