### Get all
GET http://localhost:3001/api/notes
### Get 1
GET http://localhost:3001/api/notes/1
### Delete 1
DELETE http://localhost:3001/api/notes/1

### add note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "The second note attached to user",
  "important": true,
  "userId": "6a86b8659f3197072cb70ee5"
}

### update note
PUT  http://localhost:3001/api/notes/6a732f71fe1efda1c3250b49
Content-Type: application/json

{
  "content": "HERE I AM AGAIN",
  "important": true
}

